on:
name: Deploy to Github Pages
    push:
        branches:
            - dev

jobs:
    deploy:
        name: Deploy Application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Create Node Environment
              uses: actions/setup-node@v1
              with:
                node-version: 10.x
            - name: Install Packages and Build Application
              run: |
                npm install -g @vue/cli npm
                npm install
                npm build
            - name: Deploy
              uses: s0/git-publish-subdir-action@dev
              env:
                REPO: self
                BRANCH: master
                FOLDER: dist
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
